# Generated by Django 3.2.9 on 2021-11-12 20:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=64, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('posters', models.ImageField(upload_to='media')),
                ('cast', models.ManyToManyField(to='movie.Cast')),
                ('category', models.ManyToManyField(to='movie.Category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
